    const resList = [
        {
          info: {
            id: "233804",
            name: "KFC",
            cloudinaryImageId: "f01666ac73626461d7455d9c24005cd4",
            locality: "MG Road",
            areaName: "Ravipuram",
            costForTwo: "₹400 for two",
            cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
            avgRating: 4.5,
            parentId: "547",
            avgRatingString: "4.5",
            totalRatingsString: "5K+",
            sla: {
              deliveryTime: 32,
              lastMileTravel: 7.3,
              serviceability: "SERVICEABLE",
              slaString: "30-35 mins",
              lastMileTravelString: "7.3 km",
              iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
              nextCloseTime: "2024-02-26 23:00:00",
              opened: true,
            },
            badges: {},
            isOpen: true,
            type: "F",
            badgesV2: {
              entityBadges: {
                imageBased: {},
                textBased: {},
                textExtendedBadges: {},
              },
            },
            aggregatedDiscountInfoV3: {
              header: "20% OFF",
              subHeader: "UPTO ₹50",
            },
            differentiatedUi: {
              displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
              differentiatedUiMediaDetails: {
                mediaType: "ADS_MEDIA_ENUM_IMAGE",
                lottie: {},
                video: {},
              },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
          },
          analytics: {},
          cta: {
            link: "https://www.swiggy.com/restaurants/kfc-mg-road-ravipuram-kochi-233804",
            type: "WEBLINK",
          },
        },
        {
          info: {
            id: "57445",
            name: "Subway",
            cloudinaryImageId: "63178e3e64d503a479f2a2048a474552",
            locality: "Panampilly Nagar",
            areaName: "Elamkulam",
            costForTwo: "₹350 for two",
            cuisines: ["Healthy Food", "Salads", "Snacks", "Desserts", "Beverages"],
            avgRating: 4.3,
            parentId: "2",
            avgRatingString: "4.3",
            totalRatingsString: "10K+",
            sla: {
              deliveryTime: 36,
              lastMileTravel: 7.9,
              serviceability: "SERVICEABLE",
              slaString: "35-40 mins",
              lastMileTravelString: "7.9 km",
              iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
              nextCloseTime: "2024-02-27 01:00:00",
              opened: true,
            },
            badges: {},
            isOpen: true,
            type: "F",
            badgesV2: {
              entityBadges: {
                imageBased: {},
                textBased: {},
                textExtendedBadges: {},
              },
            },
            aggregatedDiscountInfoV3: {
              header: "₹100 OFF",
              subHeader: "ABOVE ₹249",
              discountTag: "FLAT DEAL",
            },
            differentiatedUi: {
              displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
              differentiatedUiMediaDetails: {
                mediaType: "ADS_MEDIA_ENUM_IMAGE",
                lottie: {},
                video: {},
              },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
          },
          analytics: {},
          cta: {
            link: "https://www.swiggy.com/restaurants/subway-panampilly-nagar-elamkulam-kochi-57445",
            type: "WEBLINK",
          },
        },
        {
          info: {
            id: "64001",
            name: "Chicking",
            cloudinaryImageId: "86f52324ecee5fc94cbf63c4a568b672",
            locality: "P T Jacob Road",
            areaName: "Thopumpady",
            costForTwo: "₹300 for two",
            cuisines: [
              "Snacks",
              "Grill",
              "Fast Food",
              "American",
              "Pizzas",
              "Mexican",
              "Beverages",
            ],
            avgRating: 4.3,
            parentId: "251",
            avgRatingString: "4.3",
            totalRatingsString: "5K+",
            sla: {
              deliveryTime: 31,
              lastMileTravel: 2.7,
              serviceability: "SERVICEABLE",
              slaString: "30-35 mins",
              lastMileTravelString: "2.7 km",
              iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
              nextCloseTime: "2024-02-27 02:00:00",
              opened: true,
            },
            badges: {},
            isOpen: true,
            type: "F",
            badgesV2: {
              entityBadges: {
                imageBased: {},
                textBased: {},
                textExtendedBadges: {},
              },
            },
            aggregatedDiscountInfoV3: {
              header: "40% OFF",
              subHeader: "UPTO ₹80",
            },
            differentiatedUi: {
              displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
              differentiatedUiMediaDetails: {
                mediaType: "ADS_MEDIA_ENUM_IMAGE",
                lottie: {},
                video: {},
              },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
          },
          analytics: {},
          cta: {
            link: "https://www.swiggy.com/restaurants/chicking-p-t-jacob-road-thopumpady-kochi-64001",
            type: "WEBLINK",
          },
        },
        {
          info: {
            id: "123175",
            name: "Baskin Robbins - Ice Cream Desserts",
            cloudinaryImageId: "85ccae4e3576f9330af102c46ca85395",
            locality: "Panampilly Nagar",
            areaName: "Thevara",
            costForTwo: "₹199 for two",
            cuisines: ["Ice Cream"],
            avgRating: 4.7,
            veg: true,
            parentId: "5588",
            avgRatingString: "4.7",
            totalRatingsString: "1K+",
            sla: {
              deliveryTime: 32,
              lastMileTravel: 7.8,
              serviceability: "SERVICEABLE",
              slaString: "30-35 mins",
              lastMileTravelString: "7.8 km",
              iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
              nextCloseTime: "2024-02-26 23:45:00",
              opened: true,
            },
            badges: {},
            isOpen: true,
            type: "F",
            badgesV2: {
              entityBadges: {
                imageBased: {},
                textBased: {},
                textExtendedBadges: {},
              },
            },
            aggregatedDiscountInfoV3: {
              header: "10% OFF",
              subHeader: "ABOVE ₹1000",
              discountTag: "FLAT DEAL",
            },
            differentiatedUi: {
              displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
              differentiatedUiMediaDetails: {
                mediaType: "ADS_MEDIA_ENUM_IMAGE",
                lottie: {},
                video: {},
              },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
          },
          analytics: {},
          cta: {
            link: "https://www.swiggy.com/restaurants/baskin-robbins-ice-cream-desserts-panampilly-nagar-thevara-kochi-123175",
            type: "WEBLINK",
          },
        },
        {
          info: {
            id: "54676",
            name: "Gokul Oottupura",
            cloudinaryImageId: "542e37cb1343ea18ba8f0a2a43074e0f",
            locality: "Marine Drive",
            areaName: "Pallimukku",
            costForTwo: "₹200 for two",
            cuisines: ["South Indian", "North Indian", "Kerala", "Chinese"],
            avgRating: 4.5,
            veg: true,
            parentId: "434888",
            avgRatingString: "4.5",
            totalRatingsString: "10K+",
            sla: {
              deliveryTime: 40,
              lastMileTravel: 9.1,
              serviceability: "SERVICEABLE",
              slaString: "35-40 mins",
              lastMileTravelString: "9.1 km",
              iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
              nextCloseTime: "2024-02-26 22:30:00",
              opened: true,
            },
            badges: {
              imageBadges: [
                {
                  imageId: "v1695133679/badges/Pure_Veg111.png",
                  description: "pureveg",
                },
              ],
            },
            isOpen: true,
            aggregatedDiscountInfoV2: {},
            type: "F",
            badgesV2: {
              entityBadges: {
                imageBased: {
                  badgeObject: [
                    {
                      attributes: {
                        description: "pureveg",
                        imageId: "v1695133679/badges/Pure_Veg111.png",
                      },
                    },
                  ],
                },
                textBased: {},
                textExtendedBadges: {},
              },
            },
            differentiatedUi: {
              displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
              differentiatedUiMediaDetails: {
                mediaType: "ADS_MEDIA_ENUM_IMAGE",
                lottie: {},
                video: {},
              },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
          },
          analytics: {},
          cta: {
            link: "https://www.swiggy.com/restaurants/gokul-oottupura-marine-drive-pallimukku-kochi-54676",
            type: "WEBLINK",
          },
        },
        {
          info: {
            id: "56769",
            name: "Natural Ice Cream",
            cloudinaryImageId: "pzqizhikgymhcumrtytk",
            locality: "Pallimukku",
            areaName: "Pallimukku",
            costForTwo: "₹150 for two",
            cuisines: ["Ice Cream", "Desserts"],
            avgRating: 4.8,
            parentId: "2093",
            avgRatingString: "4.8",
            totalRatingsString: "5K+",
            sla: {
              deliveryTime: 33,
              lastMileTravel: 8.4,
              serviceability: "SERVICEABLE",
              slaString: "30-35 mins",
              lastMileTravelString: "8.4 km",
              iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
              nextCloseTime: "2024-02-26 23:30:00",
              opened: true,
            },
            badges: {},
            isOpen: true,
            aggregatedDiscountInfoV2: {},
            type: "F",
            badgesV2: {
              entityBadges: {
                imageBased: {},
                textBased: {},
                textExtendedBadges: {},
              },
            },
            differentiatedUi: {
              displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
              differentiatedUiMediaDetails: {
                mediaType: "ADS_MEDIA_ENUM_IMAGE",
                lottie: {},
                video: {},
              },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
          },
          analytics: {},
          cta: {
            link: "https://www.swiggy.com/restaurants/natural-ice-cream-pallimukku-kochi-56769",
            type: "WEBLINK",
          },
        },
        {
          info: {
            id: "57028",
            name: "Real Arabia",
            cloudinaryImageId: "ufkzeukq4nytfidtow5c",
            locality: "Ravipuram",
            areaName: "Ravipuram",
            costForTwo: "₹300 for two",
            cuisines: ["Arabian", "Chinese"],
            avgRating: 4.1,
            parentId: "6418",
            avgRatingString: "4.1",
            totalRatingsString: "5K+",
            sla: {
              deliveryTime: 33,
              lastMileTravel: 7.1,
              serviceability: "SERVICEABLE",
              slaString: "30-35 mins",
              lastMileTravelString: "7.1 km",
              iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
              nextCloseTime: "2024-02-27 00:30:00",
              opened: true,
            },
            badges: {},
            isOpen: true,
            type: "F",
            badgesV2: {
              entityBadges: {
                imageBased: {},
                textBased: {},
                textExtendedBadges: {},
              },
            },
            aggregatedDiscountInfoV3: {
              header: "20% OFF",
              subHeader: "UPTO ₹50",
            },
            differentiatedUi: {
              displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
              differentiatedUiMediaDetails: {
                mediaType: "ADS_MEDIA_ENUM_IMAGE",
                lottie: {},
                video: {},
              },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
          },
          analytics: {},
          cta: {
            link: "https://www.swiggy.com/restaurants/real-arabia-ravipuram-kochi-57028",
            type: "WEBLINK",
          },
        },
        {
          info: {
            id: "55090",
            name: "Burger Spot",
            cloudinaryImageId: "z4bdm7svrspopgmicc5v",
            locality: "GCDA Shopping Complex",
            areaName: "Panampilly Nagar",
            costForTwo: "₹300 for two",
            cuisines: ["Continental", "Snacks", "Beverages"],
            avgRating: 4.7,
            parentId: "4751",
            avgRatingString: "4.7",
            totalRatingsString: "1K+",
            sla: {
              deliveryTime: 36,
              lastMileTravel: 8.1,
              serviceability: "SERVICEABLE",
              slaString: "35-40 mins",
              lastMileTravelString: "8.1 km",
              iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
              nextCloseTime: "2024-02-26 23:00:00",
              opened: true,
            },
            badges: {},
            isOpen: true,
            type: "F",
            badgesV2: {
              entityBadges: {
                imageBased: {},
                textBased: {},
                textExtendedBadges: {},
              },
            },
            aggregatedDiscountInfoV3: {
              header: "30% OFF",
              subHeader: "UPTO ₹75",
            },
            differentiatedUi: {
              displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
              differentiatedUiMediaDetails: {
                mediaType: "ADS_MEDIA_ENUM_IMAGE",
                lottie: {},
                video: {},
              },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
          },
          analytics: {},
          cta: {
            link: "https://www.swiggy.com/restaurants/burger-spot-gcda-shopping-complex-panampilly-nagar-kochi-55090",
            type: "WEBLINK",
          },
        },
        {
          info: {
            id: "54749",
            name: "Ceylon Bake House",
            cloudinaryImageId: "o0kgpk2osdjinrso6zu6",
            locality: "Mg Road",
            areaName: "Chittoor Road",
            costForTwo: "₹300 for two",
            cuisines: ["South Indian", "North Indian", "Chinese", "Biryani"],
            avgRating: 4.4,
            parentId: "5436",
            avgRatingString: "4.4",
            totalRatingsString: "10K+",
            sla: {
              deliveryTime: 36,
              lastMileTravel: 9,
              serviceability: "SERVICEABLE",
              slaString: "35-40 mins",
              lastMileTravelString: "9.0 km",
              iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
              nextCloseTime: "2024-02-26 23:00:00",
              opened: true,
            },
            badges: {
              imageBadges: [
                {
                  imageId: "newg.png",
                  description: "Gourmet",
                },
              ],
            },
            isOpen: true,
            aggregatedDiscountInfoV2: {},
            type: "F",
            badgesV2: {
              entityBadges: {
                imageBased: {
                  badgeObject: [
                    {
                      attributes: {
                        description: "Gourmet",
                        imageId: "newg.png",
                      },
                    },
                  ],
                },
                textBased: {},
                textExtendedBadges: {},
              },
            },
            differentiatedUi: {
              displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
              differentiatedUiMediaDetails: {
                mediaType: "ADS_MEDIA_ENUM_IMAGE",
                lottie: {},
                video: {},
              },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
          },
          analytics: {},
          cta: {
            link: "https://www.swiggy.com/restaurants/ceylon-bake-house-mg-road-chittoor-road-kochi-54749",
            type: "WEBLINK",
          },
        },
        {
          info: {
            id: "403519",
            name: "The Burger Junction",
            cloudinaryImageId: "b79qxaca0anzkjo61my0",
            locality: "Panampilly Nagar",
            areaName: "Panampilly Nagar",
            costForTwo: "₹500 for two",
            cuisines: ["American", "Beverages"],
            avgRating: 4.6,
            parentId: "5433",
            avgRatingString: "4.6",
            totalRatingsString: "1K+",
            sla: {
              deliveryTime: 33,
              lastMileTravel: 7.4,
              serviceability: "SERVICEABLE",
              slaString: "30-35 mins",
              lastMileTravelString: "7.4 km",
              iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
              nextCloseTime: "2024-02-27 02:00:00",
              opened: true,
            },
            badges: {
              imageBadges: [
                {
                  imageId: "newg.png",
                  description: "Gourmet",
                },
              ],
            },
            isOpen: true,
            aggregatedDiscountInfoV2: {},
            type: "F",
            badgesV2: {
              entityBadges: {
                imageBased: {
                  badgeObject: [
                    {
                      attributes: {
                        description: "Gourmet",
                        imageId: "newg.png",
                      },
                    },
                  ],
                },
                textBased: {},
                textExtendedBadges: {},
              },
            },
            differentiatedUi: {
              displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
              differentiatedUiMediaDetails: {
                mediaType: "ADS_MEDIA_ENUM_IMAGE",
                lottie: {},
                video: {},
              },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
          },
          analytics: {},
          cta: {
            link: "https://www.swiggy.com/restaurants/the-burger-junction-panampilly-nagar-kochi-403519",
            type: "WEBLINK",
          },
        },
        {
          info: {
            id: "54041",
            name: "Cold Stone Creamery",
            cloudinaryImageId: "a97a58c2e292e5ed2a374f390312e2f5",
            locality: "Panampilly Nagar",
            areaName: "Panampilly Nagar",
            costForTwo: "₹200 for two",
            cuisines: ["Ice Cream", "Desserts", "Beverages"],
            avgRating: 4.4,
            veg: true,
            parentId: "3497",
            avgRatingString: "4.4",
            totalRatingsString: "5K+",
            sla: {
              deliveryTime: 32,
              lastMileTravel: 7.9,
              serviceability: "SERVICEABLE",
              slaString: "30-35 mins",
              lastMileTravelString: "7.9 km",
              iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
              nextCloseTime: "2024-02-27 01:00:00",
              opened: true,
            },
            badges: {},
            isOpen: true,
            type: "F",
            badgesV2: {
              entityBadges: {
                imageBased: {},
                textBased: {},
                textExtendedBadges: {},
              },
            },
            aggregatedDiscountInfoV3: {
              header: "40% OFF",
              subHeader: "UPTO ₹80",
            },
            differentiatedUi: {
              displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
              differentiatedUiMediaDetails: {
                mediaType: "ADS_MEDIA_ENUM_IMAGE",
                lottie: {},
                video: {},
              },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
          },
          analytics: {},
          cta: {
            link: "https://www.swiggy.com/restaurants/cold-stone-creamery-panampilly-nagar-kochi-54041",
            type: "WEBLINK",
          },
        },
        {
          info: {
            id: "121419",
            name: "Palaaram",
            cloudinaryImageId: "mz69ogfrejetsashmlrz",
            locality: "Kadavanthra",
            areaName: "Kadavanthra",
            costForTwo: "₹300 for two",
            cuisines: ["South Indian", "Chinese", "Arabian", "Kerala"],
            avgRating: 4.5,
            parentId: "18945",
            avgRatingString: "4.5",
            totalRatingsString: "10K+",
            sla: {
              deliveryTime: 38,
              lastMileTravel: 10,
              serviceability: "SERVICEABLE",
              slaString: "35-40 mins",
              lastMileTravelString: "10.0 km",
              iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
              nextCloseTime: "2024-02-26 22:45:00",
              opened: true,
            },
            badges: {},
            isOpen: true,
            type: "F",
            badgesV2: {
              entityBadges: {
                imageBased: {},
                textBased: {},
                textExtendedBadges: {},
              },
            },
            aggregatedDiscountInfoV3: {
              header: "10% OFF",
              subHeader: "ABOVE ₹1200",
              discountTag: "FLAT DEAL",
            },
            differentiatedUi: {
              displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
              differentiatedUiMediaDetails: {
                mediaType: "ADS_MEDIA_ENUM_IMAGE",
                lottie: {},
                video: {},
              },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
          },
          analytics: {},
          cta: {
            link: "https://www.swiggy.com/restaurants/palaaram-kadavanthra-kochi-121419",
            type: "WEBLINK",
          },
        },
        {
          info: {
            id: "59495",
            name: "Chiyang",
            cloudinaryImageId: "tl3i1i7m0bgdd1r6uygk",
            locality: "Kadavanthra",
            areaName: "Sahodaran Ayyappan Road",
            costForTwo: "₹400 for two",
            cuisines: ["Chinese"],
            avgRating: 4.3,
            parentId: "5445",
            avgRatingString: "4.3",
            totalRatingsString: "10K+",
            sla: {
              deliveryTime: 37,
              lastMileTravel: 9.9,
              serviceability: "SERVICEABLE",
              slaString: "35-40 mins",
              lastMileTravelString: "9.9 km",
              iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
              nextCloseTime: "2024-02-26 23:00:00",
              opened: true,
            },
            badges: {},
            isOpen: true,
            aggregatedDiscountInfoV2: {},
            type: "F",
            badgesV2: {
              entityBadges: {
                imageBased: {},
                textBased: {},
                textExtendedBadges: {},
              },
            },
            differentiatedUi: {
              displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
              differentiatedUiMediaDetails: {
                mediaType: "ADS_MEDIA_ENUM_IMAGE",
                lottie: {},
                video: {},
              },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
          },
          analytics: {},
          cta: {
            link: "https://www.swiggy.com/restaurants/chiyang-kadavanthra-sahodaran-ayyappan-road-kochi-59495",
            type: "WEBLINK",
          },
        },
        {
          info: {
            id: "73202",
            name: "Frozen Bottle - Milkshakes, Desserts And Ice Cream",
            cloudinaryImageId: "wo3thcy9n8abmjsd5ve4",
            locality: "MG Road",
            areaName: "MG Road",
            costForTwo: "₹250 for two",
            cuisines: [
              "Beverages",
              "Desserts",
              "Ice Cream",
              "Waffle",
              "Bakery",
              "Healthy Food",
            ],
            avgRating: 4.3,
            parentId: "5655",
            avgRatingString: "4.3",
            totalRatingsString: "1K+",
            sla: {
              deliveryTime: 32,
              lastMileTravel: 7.3,
              serviceability: "SERVICEABLE",
              slaString: "30-35 mins",
              lastMileTravelString: "7.3 km",
              iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
              nextCloseTime: "2024-02-27 01:00:00",
              opened: true,
            },
            badges: {},
            isOpen: true,
            type: "F",
            badgesV2: {
              entityBadges: {
                imageBased: {},
                textBased: {},
                textExtendedBadges: {},
              },
            },
            aggregatedDiscountInfoV3: {
              header: "30% OFF",
              subHeader: "UPTO ₹75",
            },
            differentiatedUi: {
              displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
              differentiatedUiMediaDetails: {
                mediaType: "ADS_MEDIA_ENUM_IMAGE",
                lottie: {},
                video: {},
              },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
          },
          analytics: {},
          cta: {
            link: "https://www.swiggy.com/restaurants/frozen-bottle-milkshakes-desserts-and-ice-cream-mg-road-kochi-73202",
            type: "WEBLINK",
          },
        },
        {
          info: {
            id: "240093",
            name: "Pizza Hut",
            cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
            locality: "Fort Kochi",
            areaName: "Fort Kochi",
            costForTwo: "₹350 for two",
            cuisines: ["Pizzas"],
            avgRating: 4.3,
            parentId: "721",
            avgRatingString: "4.3",
            totalRatingsString: "1K+",
            sla: {
              deliveryTime: 42,
              lastMileTravel: 6.7,
              serviceability: "SERVICEABLE",
              slaString: "40-45 mins",
              lastMileTravelString: "6.7 km",
              iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
              nextCloseTime: "2024-02-26 23:00:00",
              opened: true,
            },
            badges: {},
            isOpen: true,
            type: "F",
            badgesV2: {
              entityBadges: {
                imageBased: {},
                textBased: {},
                textExtendedBadges: {},
              },
            },
            aggregatedDiscountInfoV3: {
              header: "20% OFF",
              subHeader: "UPTO ₹50",
            },
            differentiatedUi: {
              displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
              differentiatedUiMediaDetails: {
                mediaType: "ADS_MEDIA_ENUM_IMAGE",
                lottie: {},
                video: {},
              },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
          },
          analytics: {},
          cta: {
            link: "https://www.swiggy.com/restaurants/pizza-hut-fort-kochi-kochi-240093",
            type: "WEBLINK",
          },
        },
        {
          info: {
            id: "53355",
            name: "Burger King",
            cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
            locality: "MG Road",
            areaName: "MG Road",
            costForTwo: "₹350 for two",
            cuisines: ["Burgers", "American"],
            avgRating: 4.5,
            parentId: "166",
            avgRatingString: "4.5",
            totalRatingsString: "10K+",
            sla: {
              deliveryTime: 47,
              lastMileTravel: 10.2,
              serviceability: "SERVICEABLE",
              slaString: "45-50 mins",
              lastMileTravelString: "10.2 km",
              iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
              nextCloseTime: "2024-02-26 23:00:00",
              opened: true,
            },
            badges: {},
            isOpen: true,
            type: "F",
            badgesV2: {
              entityBadges: {
                imageBased: {},
                textBased: {},
                textExtendedBadges: {},
              },
            },
            aggregatedDiscountInfoV3: {
              header: "ITEMS",
              subHeader: "AT ₹129",
            },
            differentiatedUi: {
              displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
              differentiatedUiMediaDetails: {
                mediaType: "ADS_MEDIA_ENUM_IMAGE",
                lottie: {},
                video: {},
              },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
          },
          analytics: {},
          cta: {
            link: "https://www.swiggy.com/restaurants/burger-king-mg-road-kochi-53355",
            type: "WEBLINK",
          },
        },
        {
          info: {
            id: "222972",
            name: "The Belgian Waffle Co.",
            cloudinaryImageId: "5116a385bac0548e06c33c08350fbf11",
            locality: "Ernakulam",
            areaName: "Ravipuram",
            costForTwo: "₹200 for two",
            cuisines: ["Waffle", "Desserts", "Ice Cream", "Beverages"],
            avgRating: 4.6,
            veg: true,
            parentId: "2233",
            avgRatingString: "4.6",
            totalRatingsString: "1K+",
            sla: {
              deliveryTime: 47,
              lastMileTravel: 7.3,
              serviceability: "SERVICEABLE",
              slaString: "45-50 mins",
              lastMileTravelString: "7.3 km",
              iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
              nextCloseTime: "2024-02-26 23:59:00",
              opened: true,
            },
            badges: {
              imageBadges: [
                {
                  imageId: "v1695133679/badges/Pure_Veg111.png",
                  description: "pureveg",
                },
              ],
            },
            isOpen: true,
            aggregatedDiscountInfoV2: {},
            type: "F",
            badgesV2: {
              entityBadges: {
                imageBased: {
                  badgeObject: [
                    {
                      attributes: {
                        description: "pureveg",
                        imageId: "v1695133679/badges/Pure_Veg111.png",
                      },
                    },
                  ],
                },
                textBased: {},
                textExtendedBadges: {},
              },
            },
            differentiatedUi: {
              displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
              differentiatedUiMediaDetails: {
                mediaType: "ADS_MEDIA_ENUM_IMAGE",
                lottie: {},
                video: {},
              },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
          },
          analytics: {},
          cta: {
            link: "https://www.swiggy.com/restaurants/the-belgian-waffle-co-ernakulam-ravipuram-kochi-222972",
            type: "WEBLINK",
          },
        },
        {
          info: {
            id: "104436",
            name: "Aryaas",
            cloudinaryImageId: "zrat1urdh1gbsf2efi6m",
            locality: "Radisson Blu Kochi",
            areaName: "Kadavanthra",
            costForTwo: "₹200 for two",
            cuisines: ["South Indian", "Beverages", "Chinese"],
            avgRating: 4.4,
            veg: true,
            parentId: "18925",
            avgRatingString: "4.4",
            totalRatingsString: "5K+",
            sla: {
              deliveryTime: 37,
              lastMileTravel: 10,
              serviceability: "SERVICEABLE",
              slaString: "35-40 mins",
              lastMileTravelString: "10.0 km",
              iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
              nextCloseTime: "2024-02-26 22:15:00",
              opened: true,
            },
            badges: {
              imageBadges: [
                {
                  imageId: "v1695133679/badges/Pure_Veg111.png",
                  description: "pureveg",
                },
              ],
            },
            isOpen: true,
            type: "F",
            badgesV2: {
              entityBadges: {
                imageBased: {
                  badgeObject: [
                    {
                      attributes: {
                        description: "pureveg",
                        imageId: "v1695133679/badges/Pure_Veg111.png",
                      },
                    },
                  ],
                },
                textBased: {},
                textExtendedBadges: {},
              },
            },
            aggregatedDiscountInfoV3: {
              header: "10% OFF",
              subHeader: "UPTO ₹40",
            },
            differentiatedUi: {
              displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
              differentiatedUiMediaDetails: {
                mediaType: "ADS_MEDIA_ENUM_IMAGE",
                lottie: {},
                video: {},
              },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
          },
          analytics: {},
          cta: {
            link: "https://www.swiggy.com/restaurants/aryaas-radisson-blu-kadavanthra-kochi-104436",
            type: "WEBLINK",
          },
        },
        {
          info: {
            id: "99740",
            name: "Nasi And Mee",
            cloudinaryImageId: "fcfbb198ec883b935e9db2582fa7a378",
            locality: "MG Road",
            areaName: "MG Road",
            costForTwo: "₹800 for two",
            cuisines: ["Pan-Asian", "Singaporean", "Malaysian", "Japanese", "Thai"],
            avgRating: 4.6,
            parentId: "19997",
            avgRatingString: "4.6",
            totalRatingsString: "1K+",
            sla: {
              deliveryTime: 44,
              lastMileTravel: 9.6,
              serviceability: "SERVICEABLE",
              slaString: "40-45 mins",
              lastMileTravelString: "9.6 km",
              iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
              nextCloseTime: "2024-02-26 23:00:00",
              opened: true,
            },
            badges: {
              imageBadges: [
                {
                  imageId: "newg.png",
                  description: "Gourmet",
                },
              ],
            },
            isOpen: true,
            aggregatedDiscountInfoV2: {},
            type: "F",
            badgesV2: {
              entityBadges: {
                imageBased: {
                  badgeObject: [
                    {
                      attributes: {
                        description: "Gourmet",
                        imageId: "newg.png",
                      },
                    },
                  ],
                },
                textBased: {},
                textExtendedBadges: {},
              },
            },
            differentiatedUi: {
              displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
              differentiatedUiMediaDetails: {
                mediaType: "ADS_MEDIA_ENUM_IMAGE",
                lottie: {},
                video: {},
              },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
          },
          analytics: {},
          cta: {
            link: "https://www.swiggy.com/restaurants/nasi-and-mee-mg-road-kochi-99740",
            type: "WEBLINK",
          },
        },
        {
          info: {
            id: "54693",
            name: "Golden Dragon",
            cloudinaryImageId: "fntkodcvkngsn5joy5mc",
            locality: "Ravipuram",
            areaName: "Ravipuram",
            costForTwo: "₹300 for two",
            cuisines: ["Chinese", "Thai"],
            avgRating: 4.4,
            parentId: "423",
            avgRatingString: "4.4",
            totalRatingsString: "1K+",
            sla: {
              deliveryTime: 42,
              lastMileTravel: 8.3,
              serviceability: "SERVICEABLE",
              slaString: "40-45 mins",
              lastMileTravelString: "8.3 km",
              iconType: "ICON_TYPE_EMPTY",
            },
            availability: {
              nextCloseTime: "2024-02-26 23:00:00",
              opened: true,
            },
            badges: {
              textExtendedBadges: [
                {
                  iconId: "guiltfree/GF_Logo_android_3x",
                  shortDescription: "options available",
                  fontColor: "#7E808C",
                },
              ],
            },
            isOpen: true,
            aggregatedDiscountInfoV2: {},
            type: "F",
            badgesV2: {
              entityBadges: {
                imageBased: {},
                textBased: {},
                textExtendedBadges: {
                  badgeObject: [
                    {
                      attributes: {
                        description: "",
                        fontColor: "#7E808C",
                        iconId: "guiltfree/GF_Logo_android_3x",
                        shortDescription: "options available",
                      },
                    },
                  ],
                },
              },
            },
            differentiatedUi: {
              displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
              differentiatedUiMediaDetails: {
                mediaType: "ADS_MEDIA_ENUM_IMAGE",
                lottie: {},
                video: {},
              },
            },
            reviewsSummary: {},
            displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
            restaurantOfferPresentationInfo: {},
          },
          analytics: {},
          cta: {
            link: "https://www.swiggy.com/restaurants/golden-dragon-ravipuram-kochi-54693",
            type: "WEBLINK",
          },
        },
      ];

      export default resList;